site_name: dahak-taco
site_url: https://dahak-metagenomics.github.io/dahak-taco
repo_name: dahak-taco
repo_url: https://github.com/dahak-metagenomics/dahak-taco
edit_uri: ""

copyright: 'Copyright &copy; 2018 <a href="http://ivory.idyll.org/lab/">Lab for Data Intensive Biology</a> at UC Davis'

# change directory names here
docs_dir: docs
site_dir: site

theme:

  # the next 2 lines are required to use the DIB version
  name: null
  custom_dir: 'mkdocs-material-dib/material'

  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'orange'
    accent: 'orange'
  
  # fun logos! see https://material.io/icons/
  logo:
    icon: 'group_work'

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# this will add docs/css/custom.css to all your docs
extra_css:
  - css/custom.css

# give a title for each page
pages:
  - 'Index' : 'index.md'
  - 'Installation and Usage' : 'InstallationUsage.md'
  - 'Quick Start' : 'Quickstart.md'
  - 'AWS Setup for Walkthroughs' : 'AWSSetup.md'
  - 'Snakemake Rules' : 'SnakemakeRules.md'
  - 'Creating Workflows' : 'Workflows.md'
  - 'Documentation' : 'Documentation.md'
  - 'Snakemake Development' : 'Development.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
